### ISSUE TITLE
Bug: crs epsg code

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt_wflow#108]
This doesn't seem to work with the new crs definition:
https://github.com/Deltares/hydromt_wflow/blob/4f2639259f7ffc2e4489a991cd0cefc02a1f6227/hydromt_wflow/wflow.py#L764

**Comment by DirkEilander** [comment]
Thanks for this bug report! What do you mean "the new crs definition"? Is that a change we made in the Model class or some external changes?

**Comment by hboisgon** [comment]
I guess we changed something but didn't dig yet to know what. This is called each time you update gauges using a direct csv file (no data catalog) so used quite a lot, even in our notebooks but unfortunately not with our automatic test :/

**Comment by hboisgon** [comment]
Apparently in rio.crs returns pyproj.CRS instead of rasterio.crs.CRS object. The first one does not have is_epsg_code attribute but has a to_epsg() method
