### ISSUE TITLE
unbound local error in rivers method

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt_wflow#113]
The else statement in rivers should be lowered to fix a potential unbound local error if no river geoms is found and not river mask is found. 

https://github.com/Deltares/hydromt_wflow/blob/4f2639259f7ffc2e4489a991cd0cefc02a1f6227/hydromt_wflow/wflow.py#L2107

This error is raised when building the docs for the update_model_gauges.ipynb example (see action referenced below), but was not raised before. We should carefully check why both the rivers geom and river mask map are not available anymore!

https://github.com/Deltares/hydromt_wflow/actions/runs/3187682388/jobs/5260892285

**Comment by hboisgon** [comment]
This seems to be linked to #108 , the model with updated gauges is not created so no rivers can be found. But anyway indeed the unbound local error should be removed in self.rivers
