### ISSUE TITLE
Cannot find automatically the LULC mapping file for ESA worldcover

### ISSUE THREAD

**Issue by AlessiaRiveros** [Deltares/hydromt_wflow#135]
When updating my wflow model with the ESA worldcover:

hydromt update wflow wflow_250m -o ./wflow_250m_ESA -c setup_lulcmaps --opt lulc_fn=esa_worldcover --dd -v

I get an error:

2022-11-24 17:57:51,443 - update - wflow - ERROR - LULC mapping file not found: C:\Users\riveros\Miniconda3\envs\hydromt-wflow\lib\site-packages\hydromt_wflow\data\lulc\esa_worldcover_mapping.csv

I've worked around it by copying the csv file from: 

https://github.com/Deltares/hydromt_wflow/tree/main/hydromt_wflow/data/lulc

and specifying a hard path instead:

hydromt update wflow wflow_250m -o ./wflow_250m_ESA -c setup_lulcmaps --opt lulc_fn=esa_worldcover --opt lulc_mapping_fn=c:\Projects\hydromt-wflow\hydromt\static_maps\esa_worldcover_mapping.csv --dd -v

and the wflow model gets correctly updated. I would have expected hydromt wflow to find this mapping table automatically.

I have hydromt 0.6.0 and hydromt_wflow 0.2.0

**Comment by hboisgon** [comment]
Hi Alessia, 
ESA Worldcover (and the related mapping table) was added with hydromt_wflow 0.2.1. If you update your hydromt_wflow, the file should be found automatically.
You can always indeed put a hard path which in my view is not so bad to get to know the values inside the mapping tables. We added DataFrame support in hydromt datacatalog in version 0.6.0 so the lulc_mapping_fn will soon become a required argument.

**Comment by DirkEilander** [comment]
I did notice that "esa_worldcover" is not mentioned in the docstring as one of the options for which a mapping table is automatically found. This might be good to add.
