### ISSUE TITLE
Support rating curves tables (csv) for Lake modelling

### ISSUE THREAD

**Issue by shartgring** [Deltares/hydromt_wflow#148]
Original: It is possible to add hq and sh tables to a Wflow model using .csv files (see also https://deltares.github.io/Wflow.jl/stable/model_docs/lateral/waterbodies/). However, they are not recognized by HydroMT and thus not copied along when updating or clipping a Wflow model

Edit: support rating curve tables for lake modelling within hydromt wflow
Allow to prepare lake modelling using rating curves when available:

- [ ] rating curves supplied in simple csv format with lake ID in the filename (need to adapt GeoDataset reader?)
- [ ] add to a hydromt object (not sure which one yet?)
- [ ] create maps for LakeStoreFunc and LakeOutflowFunc instead of default value in toml (see #149 )
- [ ] add readers and writers (should allow updating automatically)
- [ ] update clipping of lake reservoirs to potentially remove some of the tables
- [ ] additionnal: this method could also be used for reservoir - maybe add a filter column to setup_reservoirs and setup_lakes method to filter for lakes and reservoirs (so that one data source can be used for both) -> shall we do that in the data catalog or with filter argument like hydrolib example?

**Comment by hboisgon** [comment]
Hi @shartgring . Correct, we only support one option for modelling lakes in HydroMT which is the Modified Puls approach. So we do not recognise the csv files or also the LakeOutflowFunc and LakeStorFunc parameters as mentioned in your other issue #149. Would be good to support the other approaches as well indeed.
