### ISSUE TITLE
Setup precip forcing can lead to pandas to_timedelta error

### ISSUE THREAD

**Issue by RubenImhoff** [Deltares/hydromt_wflow#151]
Hi all,

When using hydromt to set up a new wflow_sbm model, the setup_precip_forcing tool gives the following error:
![image](https://user-images.githubusercontent.com/31476760/213682566-eceda0b0-9a1f-4cda-babf-d639166b0490.png)

Looks like pandas to_timedelta is receiving a string, while it shouldn't. @DirkEilander suggested to simply add a int() around the get_config() in this function. 

For reproducibility:  
- hydromt v.0.6.1.dev used
- hydromt-wflow v.0.2.2.dev used
- pandas v1.5.2 used
- Setup_config was as follows:
```[setup_config]
starttime = 2009-01-01T00:00:00
endtime = 2009-06-01T00:00:00
timestepsecs = 86400
input.path_forcing = inmaps-era5-2010.nc
chunksize = 1 
```

**Comment by DirkEilander** [comment]
This is fixed in the above referenced PR in HydroMT core
