### ISSUE TITLE
Unable to export and rewrite results using Piave_subbasin

### ISSUE THREAD

**Issue by musmanliaqat0321** [Deltares/hydromt_wflow#154]
[examples.zip](https://github.com/Deltares/hydromt_wflow/files/10805239/examples.zip)
I am quite beginner using wflow hydrological modeling scheme. 
1) Initially, I installed  hydromt-wflow using following link:
https://deltares.github.io/hydromt/latest/getting_started/installation.html#installation-guide
2) I am trying to run example attached. The model is working but I unable to see outputs in cross ponding folders. 
<img width="664" alt="model" src="https://user-images.githubusercontent.com/126057655/220675465-295029fd-5e6b-4e0f-a4e3-11c4c65f68dc.PNG">
<img width="882" alt="model_output results" src="https://user-images.githubusercontent.com/126057655/220675474-42ca9dc7-90df-4a3b-a656-8e0d7067274a.PNG">
Anyone guide me about it. Thanks

**Comment by DirkEilander** [comment]
Note that HydroMT-Wflow only helps you to build a model schematization, i.e. prepare all model inputs. To actually run the model you need the Wflow model kernel, see for moer info https://deltares.github.io/Wflow.jl/dev/ .  Hope this answers your question. Feel free to re-openen this issue if I misunderstood your question.
