### ISSUE TITLE
linux test fail on soilgrids map with large differences

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt_wflow#17]
My guess is that these differences originate from the `raster.interpolate_na` method. Perhaps the fill values are not parsed correctly? Or the grid coordinates have rounding errors causing differences in the nearest interpolation at cells with missing values.

see https://github.com/Deltares/hydromt_wflow/runs/2544491332 
relates to #4 

for wflow: 

```
AssertionError: 14 invalid maps: {
  'SoilThickness': 'diff: -14.7917 (3 cells: [(12.066667, 46.550000), (11.850000, 46.433333), (12.333333, 46.133333)])', 
  'SoilMinThickness': 'diff: -14.7917 (3 cells: [(12.066667, 46.550000), (11.850000, 46.433333), (12.333333, 46.133333)])', 
  'KsatVer': 'diff: 1.7397 (12 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (11.850000, 46.433333), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.316667, 46.100000), (12.333333, 46.100000), (12.216667, 45.983333), (12.233333, 45.983333)])', 
  'KsatVer_0.0cm': 'diff: 1.7397 (12 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (11.850000, 46.433333), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.316667, 46.100000), (12.333333, 46.100000), (12.216667, 45.983333), (12.233333, 45.983333)])', 
  'KsatVer_5.0cm': 'diff: 1.2059 (11 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (11.850000, 46.433333), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.333333, 46.100000), (12.216667, 45.983333), (12.233333, 45.983333)])', 
  'KsatVer_15.0cm': 'diff: 0.2921 (12 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (11.850000, 46.433333), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.316667, 46.100000), (12.333333, 46.100000), (12.216667, 45.983333), (12.233333, 45.983333)])', 
  'KsatVer_30.0cm': 'diff: 0.5855 (11 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (11.850000, 46.433333), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.333333, 46.100000), (12.216667, 45.983333), (12.233333, 45.983333)])', 
  'KsatVer_60.0cm': 'diff: 1.1310 (12 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (11.850000, 46.433333), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.316667, 46.100000), (12.333333, 46.100000), (12.216667, 45.983333), (12.233333, 45.983333)])', 
  'KsatVer_100.0cm': 'diff: 0.7625 (12 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (11.850000, 46.433333), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.316667, 46.100000), (12.333333, 46.100000), (12.216667, 45.983333), (12.233333, 45.983333)])', 
  'KsatVer_200.0cm': 'diff: 0.2181 (11 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.316667, 46.100000), (12.333333, 46.100000), (12.216667, 45.983333), (12.233333, 45.983333)])', 
  'M_original_': 'diff: 0.2448 (12 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (11.850000, 46.433333), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.316667, 46.100000), (12.333333, 46.100000), (12.216667, 45.983333), (12.233333, 45.983333)])', 
  'M_': 'diff: 0.2448 (12 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (11.850000, 46.433333), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.316667, 46.100000), (12.333333, 46.100000), (12.216667, 45.983333), (12.233333, 45.983333)])', 
  'M_original': 'diff: 0.2291 (11 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (11.850000, 46.433333), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.333333, 46.100000), (12.216667, 45.983333), (12.233333, 45.983333)])', 
  'M': 'diff: 0.2291 (11 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (11.850000, 46.433333), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.333333, 46.100000), (12.216667, 45.983333), (12.233333, 45.983333)])'
}
```

for wflow_sediment
```
AssertionError: 4 invalid maps: {
  'PercentClay': 'diff: -0.0156 (12 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (11.850000, 46.433333), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.316667, 46.100000), (12.333333, 46.100000), (12.216667, 45.983333), (12.233333, 45.983333)])', 
  'PercentSilt': 'diff: 0.0085 (11 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (11.850000, 46.433333), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.316667, 46.100000), (12.333333, 46.100000), (12.233333, 45.983333)])', 
  'PercentOC': 'diff: -0.0092 (12 cells: [(12.066667, 46.550000), (12.083333, 46.550000), (11.833333, 46.516667), (11.850000, 46.433333), (12.016667, 46.400000), (12.066667, 46.166667), (12.333333, 46.133333), (12.350000, 46.116667), (12.316667, 46.100000), (12.333333, 46.100000), (12.216667, 45.983333), (12.233333, 45.983333)])', 
  'ErosK': 'diff: -0.0094 (1 cells: [(11.850000, 46.433333)])'
}
```

**Comment by DirkEilander** [comment]
This issue seems to be resolved with `raster.interp_na('linear')` instead of `raster.interp_na('nearest')`, see soilgrids.py in https://github.com/Deltares/hydromt_wflow/pull/16/commits/fb8e56099b96d8a7d405afc92af4039627ed267e

Note that the linear interpolation is much slower compared to the nearest interpolation. I'm also not completely clear about why nearest interpolation yields different results on linux vs windows, but it must be related with rounding errors in the coordinates which are calculated for the geotiffs and the model res and cause a different cell to be the 'nearest neighbor'. It might be worth checking if more precision in the model resolution also solves the error.

There are a few options to go forward with this info:
- keep nearest and see if we can solve the issue in interp_na - no clue yet how & might take a lot of time - or more precise model resolution.
- keep nearest and allow change the tests (e.g. test on model mean of each map), this might however prevent us from spotting other errors in the future.
- use interp_na with linear - this will slow down the model building. We could do a simple 'optimization' by checking if all the calls to interp_na are required and if all interp_na calls are required to use linear interpolation. 

@hboisgon @laurenebouaziz @verseve what do you think?

**Comment by verseve** [comment]
I would say start with option 1, keep nearest and check what happens at these cells. In my opinion a difference in test results with interp_na with nearest between Linux and Windows should not be a reason to use another interpolation method. 

Option 2 sounds good when it indeed takes too much time/ no clue how to resolve it, you could also ignore the specific cells (~10) where this issue occurs. I guess ~10 cells is a very small part of the complete grid?

**Comment by DirkEilander** [comment]
I suggest to only test on windows for now and keep the nearest interp_na method. We will need to rewrite this method to fix the problem. We could try to use the code underlying scipy griddata to fix it. Some inspiration: https://stackoverflow.com/questions/20915502/speedup-scipy-griddata-for-multiple-interpolations-between-two-irregular-grids

**Comment by laurenebouaziz** [comment]
Yes also good option to only test on windows or try to rewrite the function. Otherwise, I think the alternative proposed by Hélène to keep nearest as default option but apply linear for the tests is also a quick fix, which in addition enables us to keep the nearest method. 
I am ready to commit the changes in soilgrids2, should I add the option for method of linear interp or we keep it as is for now?

I will create another issue to explain the preprocessing steps and changes I made for the soilgrids2 workflow.
