### ISSUE TITLE
Basin_index data

### ISSUE THREAD

**Issue by Safa136** [Deltares/hydromt_wflow#178]
I wonder where I can download the merit_hydro_index, as I am using merit-hydro for hydrography function and require data for basin-index corresponding to merit hydro data.

**Comment by DirkEilander** [comment]
The basin index file is basically a vector representation of (the bounding box of) your basins. This file is (only) needed to be able to load only the required area when delineating a subbasin. 

I recommend using the IHU upscaled 30 arcsec (~1km) resolution MERIT Hydro which includes a 30sec_basins.gpkg basin index file. You can download this data from [Zenodo](https://zenodo.org/record/7936280#.ZGHfEHZBwuU) . Alternatively, you create you're own basin index file by vectorizing a grid with unique IDs per basin obtained using e.g. the [pylfwdir.basins](https://deltares.github.io/pyflwdir/latest/_examples/basins.html) method.

**Comment by Safa136** [comment]
Thank you DirkEilander.

**Comment by Safa136** [comment]
What about era5_orography data? I believe this is the elevation data! but I cant find it to download.

**Comment by hboisgon** [comment]
The orography data for ERA5 is actually geopotential and because it’s a ERA5 input rather than output, you can download it from the documentation: [https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation#ERA5:datadocumentation-Table1](https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation#ERA5:datadocumentation-Table1)
In that table, it is line 9 geopotential.

**Comment by Safa136** [comment]
Thank you very much Hboisgon.

**Comment by Safa136** [comment]
1. I got this error when trying to setup wflow using one point (x,y) in the basin:

    Usage: hydromt build [OPTIONS] MODEL MODEL_ROOT REGION
    Try 'hydromt build --help' for help.

    Error: Invalid value for '-r' / '--res': "{'basin': [6.5276510,53.3277350]}" is not a valid float.

2. I tried a basin with a unique basin ID. I got the following error:

    Usage: hydromt build [OPTIONS] MODEL MODEL_ROOT REGION
    Try 'hydromt build --help' for help.

    Error: Invalid value for '-r' / '--res': "{'basin': [230000090]}" is not a valid float.

3. I tried a basin with (xmin,ymin,xmax,ymax). I got the following error:
    Usage: hydromt build [OPTIONS] MODEL MODEL_ROOT REGION
    Try 'hydromt build --help' for help.

     Error: Invalid value for '-r' / '--res': "{'basin': [-7.38, 53.303, -6.24, 53.97]}" is not a valid float.

what to do? I appreciate your help!

**Comment by Safa136** [comment]
Please help with this error:

build - main - ERROR - Geotransform and/or shape do not match. 
xarray.core.merge.MergeError: Geotransform and/or shape do not match

**Comment by hboisgon** [comment]
Hi @Safa136 how did you preapre your merit_hydro/{variable}.tif file? Note that for hydromt to consider a dataset has the same data source (data catalog entry), all variables must have exactly the same grid definition (CRS, resolution, x, y coordinates). If you merge several tif files together (for example in QGIS), you may easily make mistake and get merged tif variables in slightly different grid. This is why we recommend to use the vrt format espeically for Merit Hydro. You can learn more here how to produce a vrt file based on several tifs: https://deltares.github.io/hydromt/latest/user_guide/data_types.html#multi-variable-virtual-raster-tileset-vrt

**Comment by hboisgon** [comment]
By the way, input data related issues are reported in issue #157. I'll now close this one to have one single issue on the topic. If you find something else related to input data, please post there and for new issue, just open a new one!
