### ISSUE TITLE
Model build - HydroMT errors after update to v 0.7.1

### ISSUE THREAD

**Issue by Starphire1** [Deltares/hydromt_wflow#186]
Errors on wflow model build with HydroMT tools experienced after updating HydroMT to v 0.7.1 16/6/2023.
Subbasin, basin and 'r' model resolution are depreciated or give errors.

Link to guide: https://github.com/Deltares/hydromt_wflow/blame/main/docs/user_guide/wflow_build.rst 

HydroMT model build errors:

- hydromt.error.DeprecatedError: DeprecationError: '-r' is used for region, resolution is deprecated
- Error: Got unexpected extra argument ({'subbasin': [151.99304, -25.28844], 'bounds': [147, -28, 153.8, -23.6], 'uparea': 50})
- Error: Got unexpected extra argument ({'subbasin': [151.99304, -25.28844]})
- Error: Got unexpected extra argument ({'basin': [151.99304, -25.28844]})
#167 
@hboisgon @markhegnauer

**Comment by hboisgon** [comment]
Hi @Starphire1 

Indeed there was some changes to the hydromt command line with hydromt release 0.7.0. Sorry if this was not too clear.

What changed:

- The region argument (eg subbassin x,y) became optional so it now needs either the ``-r`` or ``--region`` shortcuts: ``-r "{'basin': [151.99, -25.29]}"``
- The resolution can be set in the wflow_build.ini file or still in the command line but in a little more complex way: ``--opt setup_basemaps.res=0.009``

We put a note in the hydromt_wflow docs about it: https://deltares.github.io/hydromt_wflow/latest/user_guide/wflow_build.html

Hope this helps!
