### ISSUE TITLE
Assess impact of hydromt change in raster.clip_geom 

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt_wflow#187]
Because we were running into memory issues when using geometry clipping with higher res raster dataset, we have decided to implement a change in hydromt-core. Previously the `get_rasterdataset` function would always provide a mask clip in the coordinates if a geometry was passed, which was leading to memory errors. With this change, it will no longer include this mask by default. I hope i'm explaining this clearly, for more information see the issue and it's corresponding PR: 

- https://github.com/Deltares/hydromt/issues/350
- https://github.com/Deltares/hydromt/pull/434

**Comment by DirkEilander** [comment]
We want to merge and release our [fix](https://github.com/Deltares/hydromt/pull/424) asap. However it would be good to do a quick screening with that hydromt core branch to see how this affects hydromt-wflow. Is this something that you @JoostBuitink or @B-Dalmijn could pickup?

**Comment by DirkEilander** [comment]
Note that this PR is now merged in the HydroMT core main branch and will be released next week. It'd be great if someone could help and do a quick check if this causes issues for HydroMT-Wflow before the release.

**Comment by JoostBuitink** [comment]
I will try to take a quick look at this next week! I am currently quite busy (and @B-Dalmijn is taking next week off), so I am not sure whether we'll be able to fully test this next week. In any case, if problems do arise, we can always fix hydromt to the current release version, right?
