### ISSUE TITLE
Better reservoir workflow and new data

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt_wflow#20]
Add GRanD v1.3
Review reservoir and lakes methods

**Preprocess lake/reservoir database**
Building intbls for reservoirs is based on the global_wflow library, downloads HydroEngine timeseries each time and do some very specific calculations using attributes that may not be present in every datasets.
The idea is to maybe create a preprocess script that adds all parameters needed for wflow directly to the database and then hydroMT just reads directly the parameters from the database and doesn't do any intermediate calculations to produce the intbl files.
Note that apparently HydroEngine needs to have a HydroLAKES ID to be able to download JRC timeseries.

**documentation minimal requirements and improve consistency of column names and units in reservoirs/lakes/glaciers**
To be able to easily update the current shape data or use user supplied shape data for the reservoirs/lakes/glaciers it would be good to align the naming and units in these methods and document the minimal required data.

Currently the workflows are very data specific. for instance the area column for lakes/reservoirs is called 'Area_avg' with unit m2, while the area column for glaciers is called 'AREA' with unit km2.

**Comment by DirkEilander** [comment]
While setup_reservoirs does accept any input data, for setup_lakes and setup_glaciers the names of the input data are hard coded. 

This can give some funny error when trying to modify hydro_lakes properties in a local copy of the data and passing it with a local yml file, while the data_catalog.yml file in the model root already has a hydro_lakes entry which will overwrite the entry in your local file.
