### ISSUE TITLE
Config ini files should be translated to yml

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt_wflow#207]
### HydroMT-Wflow version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT-Wflow.

### Reproducible Example

NA

### Current behaviour

The wflow config models are currently still in ini format which is deprecated in hydromt-core and will be removed in the 1.0 release.  

### Desired behaviour

To maintain good support the current config files should be translated to a supported file format such as toml or yaml.

**Comment by DirkEilander** [comment]
This is important for users to be able to select the version of a dataset, which should become common practice for reproducibility! I recommend updating this asap.

```yml
setup_soilmaps:
  soil_fn:
    name: soilgrids
    version: 2017
```

instead of 
```ini
[setup_soilmaps]
soil_fn=soilgrids
```

**Comment by DirkEilander** [comment]
> To maintain good support the current config files should be translated to a supported file format such as toml or yaml.

In response to @savente93 issue description: Note that toml is not supported for configuration files and the format should be yml.

**Comment by savente93** [comment]
Core does support toml configuration, but I don't really care which is used, so if you care that it's specifically yaml that's fine by me

**Comment by DirkEilander** [comment]
Apologies @savente93, you are right!! However, I'd be in favour of having a single format supported by HydroMT to keep things simple for ourselves and users. And either-way, this won't be the 'old' ini-format.
