### ISSUE TITLE
Documentation Bug (probably progressbar)

### ISSUE THREAD

**Issue by dalmijn** [Deltares/hydromt_wflow#233]
### HydroMT-Wflow version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT-Wflow.

### Reproducible Example

Build the docs.

### Current behaviour

Produces an error looking like this for example pages, as a result of updating or building the models:
![image](https://github.com/Deltares/hydromt_wflow/assets/92092029/208bbd88-fa98-4c29-ae5b-ed06517a78b5)

This makes the pages look like this:
![image](https://github.com/Deltares/hydromt_wflow/assets/92092029/16fa1ad9-8609-48b0-9a3b-0e13f7d9a6ce)

I'd say it has to do with the progress bars.

### Desired behaviour

Normal looking examples pages at this point.

**Comment by hboisgon** [comment]
Strange... Not sure if it's only the progress bar though, seems the log is also split into several text windows instead of just the one.
I see this is also happening in hydromt core: https://deltares.github.io/hydromt/latest/_examples/working_with_models_basics.html

So maybe something to do with sphinx?

**Comment by JoostBuitink** [comment]
I think this is related to this issue https://github.com/jupyter/nbconvert/issues/2092. Note some of the linked issues in there as well, pinning nbconvert to an older version appears to be a (temporary) fix.

**Comment by dalmijn** [comment]
@JoostBuitink, Thanks for the suggestion, this looks like it does the trick!
