### ISSUE TITLE
Release hydromt_wflow v0.5.0

### ISSUE THREAD

**Issue by JoostBuitink** [Deltares/hydromt_wflow#237]
Given the latest improvements and fixes (mainly the switch from .ini to .yml files, and improved dealing with the NoDataStrategy) I think it would be good to do a release soon. The switch from .ini to .yml is a relatively big change for our users, hence I think a new major version is a good signal. 

At least these two PRs (https://github.com/Deltares/hydromt_wflow/pull/227 and https://github.com/Deltares/hydromt_wflow/pull/229) should be included before we release

Just for completeness, for https://github.com/Deltares/hydromt_wflow/pull/229, we need to fix hydromt to `>=0.9.3,<0.10` when we do the release.

Are there any other fixes that we want to include for this release? I'd prefer to release as soon as possible, as it once again allows users to use the same `build.yml` file regardless of whether the region contains lakes/reservoirs/glaciers.

**Comment by hboisgon** [comment]
It's a quick docs one but maybe also include #238
