### ISSUE TITLE
Link LAI and land cover classes

### ISSUE THREAD

**Issue by JoostBuitink** [Deltares/hydromt_wflow#243]
### Kind of request

Adding new functionality

### Enhancement Description

Currently, there is no direct link between the LAI data and the land cover classes. As long as we are simulating historical periods, this is no problem. But when performing simulations with land cover changes, these changes are not reflected in the LAI data.

Ideally, changing the land cover data (or a certain class, e.g. from urban to forest, or vice versa) should also be accompanied by a change in LAI. This would require a link between land cover classes and a typical (monthly) cyclic LAI pattern, which could be achieved via a "lookup-table". However, as the timing of the growing season shifts depending on the latitude, this should also be taken into account when linking the LAI to land cover classes.

### Use case

In the case where you want the perform simulations with completely different land cover data: either different data-source, or by changing certain land cover classes (nature based solutions, for example).

**Comment by hboisgon** [comment]
One suggestion:

1. Read MODIS and allow the user to load a larger extent than his basin
2. Derive cyclic LAI from MODIS
3. Open the landuse map (ideally at original resolution) and try and derive LAI value per land use type
4. Apply these values to the landuse (mapping table approach)
5. Optionally save the derived LAI values per land use type as tables for re-use in scenarios

Add a second method to only derive LAI from mapping values to landuse
Optionally: try and see if we can prepare pre-defined tables for Northern vs Southern Hemisphere. There might be better ways to split (per latitude or basin but may take more time or research).
