### ISSUE TITLE
Wrong equation for residual moisture content seems to be used

### ISSUE THREAD

**Issue by jensdebruijn** [Deltares/hydromt_wflow#285]
### HydroMT-Wflow version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT-Wflow.

### Reproducible Example

-

### Current behaviour

The function in hydromt-wflow https://github.com/Deltares/hydromt_wflow/blob/29e6c685044d3c67d7e10b1038a625bad0e76b21/hydromt_wflow/workflows/ptf.py#L173 states that the residual moisture content is estimated, but the used equation is actually for the wilting point. See S1 of https://bsssjournals.onlinelibrary.wiley.com/doi/full/10.1111/ejss.12192.

![image](https://github.com/user-attachments/assets/317a7736-00f8-4dcf-9623-19084fdf1403)

- 

### Desired behaviour

-

**Comment by verseve** [comment]
Thanks for reporting this issue. 

This is indeed the equation for the wilting point. @RubenImhoff: do you perhaps know why this equation was selected for residual water content? I guess for coarse textured soils this equation is most probably fine, but for fine textured soils it may overestimate residual water content. In the Toth paper theta_r is estimated based on only sand content (RT method). Additionally, we also used a PTF of Rawls and Brakensiek to estimate theta_r (as part of Python scripts before hydromt_wflow).

Would be good to look into this further and decide if we need to replace this equation. Furthermore, would be good to discuss if we want to support different PTFs (probably also concerns other parameters like theta_s).
