### ISSUE TITLE
write_staticmaps_pcr fails because rasterio not imported in gis_utils.py

### ISSUE THREAD

**Issue by laurenebouaziz** [Deltares/hydromt_wflow#30]
the function write_staticmaps_pcr fails with message:

File "c:\users\bouaziz\appdata\local\continuum\anaconda3\envs\hydromt-wflow\lib\site-packages\hydromt\gis_utils.py", line 366, in write_map
    with rasterio.open(raster_path, "r+") as dst:
NameError: name 'rasterio' is not defined

I think because rasterio is not imported in gis_utils from hydromt-core :

        if crs is not None:
            with rasterio.open(raster_path, "r+") as dst:
                dst.crs = crs

**Comment by hboisgon** [comment]
This is now fixed in hydromt core
