### ISSUE TITLE
waterbodies.py (reservoir parameter calculation)

### ISSUE THREAD

**Issue by jurianbeunk** [Deltares/hydromt_wflow#35]
Line 259 in waterbodies.py:
`dam_height = np.nanmax([gdf["Dam_height"].iloc[i], 0.0]`
(or similar parameter calculations)

Will raise np.nanmax error `TypeError: '>=' not supported between instances of 'NoneType' and 'float'` when `rdf` contains NoneType data (i.e. no data). 

Applying `gdf = gdf.fillna(value=np.nan)` before the parameter calculation loop, will result in np.nanmax returning 0.0 like it is supposed to and prevent the error from occuring.

**Comment by hboisgon** [comment]
Closed with #130
