### ISSUE TITLE
south and east edge of slope map missing

### ISSUE THREAD

**Issue by visr** [Deltares/hydromt_wflow#53]
If I create the staticmaps based on a fixed bounding box, like so:

```
hydromt build wflow "./wflow_test_base" "{'bbox': [34.8, 29.0, 39.4, 33.7]}" -r 0.00833 -v --dd
```

Then I can see that the bottom row and rightmost column of the slope map are missing. See here for instance the colored subcatchments sticking out under the grayscale slope map:
![image](https://user-images.githubusercontent.com/4471859/134246626-b481f58f-a275-4a01-8a4c-8eddce83fb44.png)

I understand that to calculate slope you need neighboring cells as well, though it's a bit unfortunate because Wflow cannot run with missing slopes on active cells. Is there anything else we can do here?

I ran this using the main branch of hydromt and hydromt_wflow.

**Comment by DirkEilander** [comment]
Thanks for the report @visr. I'm surprised by this behavior as the edges are explicitly dealt with in the slope method, see https://github.com/Deltares/pyflwdir/blob/main/pyflwdir/dem.py#L234 We need to debug this case to understand how this is caused. Did you encounter this at more locations?

**Comment by hboisgon** [comment]
Hi @visr , additionally to build wflow models, we recommend not to use the 'bbox' or 'geom' options but rather the 'basins' or 'subbasins' option, in your case: 

`hydromt build wflow "./wflow_test_base" "{'basin': [34.8, 29.0, 39.4, 33.7]}" -r 0.00833 -v --dd`

With this, hydromt will derive every basin that intersects with the bbox. The 'bbox' option just does a cut of the DEM without searching for potential upstream areas of the basins outside of the bbox.

**Comment by markhegnauer** [comment]
Somewhat similar issue for a model I build for the UK. In this case there is LDD, but now DEM and SLOPE. After discussion with Dirk, added in wflow.py the following temporal solution to cover all cells within the mask in the slope map with 0.0. Seems to solve the issue for my case.

ds_topo['lndslp'] = np.maximum(ds_topo['lndslp'], 0.0)

**Comment by DirkEilander** [comment]
Thanks @markhegnauer. I suggest to implement this fix before the next release but keep this thread open to research why this occurs. Could you create a PR for this or would you like me to do it?

**Comment by hboisgon** [comment]
@DirkEilander do you think this is still relevant?

**Comment by DirkEilander** [comment]
This is from a while back - I'm not sure if it's still relevant.
We can simple run Martijn's example to find out.

**Comment by visr** [comment]
I tried to run it on the latest version but can't figure out how to update the syntax, the docs focus on basin and subbasin. I'll just close this. #70 mentioned fixing this so probably it is done.
