### ISSUE TITLE
Error in lake_b parameter

### ISSUE THREAD

**Issue by JoostBuitink** [Deltares/hydromt_wflow#61]
When creating a wflow_sbm model with lakes, hydromt_wflow can produce invalid lake parameters. When `LakeAvgOut = 0`, this will lead to a `Lake_b` parameter of `0`. This results in a model that cannot run. Manually changing the `Lake_b` value solves the issue. Perhaps set a default value for `Lake_b` when `LakeAvgOut = 0`?

**Comment by DirkEilander** [comment]
Thanks @JoostBuitink  for the issue report. Any idea when or where `LakeAvgOut = 0` occurs?  I'm wondering if this should be solved at the hydroMT or data itself.  And do you have a suggestion for a good default value?

**Comment by JoostBuitink** [comment]
It occurred in a lake in Jordan, id 15213. It appears to be a data-issue, as the dis_avg is set to zero in the HydroLAKES data as well. As a default value: probably something small, just to prevent any errors in wflow. I currently used 0.002 for lake 15213. Perhaps it is possible to link the default value to the lake area, but I suspect most lakes with dis_avg = 0 are probably rather small.

**Comment by markhegnauer** [comment]
Same issue occured in Australia for several basins. In many cases, Lake_b was 0.0. I guess this comes from a LakeAvgOut=0.0 in arid basins and/or for small lakes. I think this is actually a data issue, but might be easier to solve with a default Lake_b parameter value > 0.0. 

Attached the example of Australia with all lakes (blue) and lakes with Dis_avg = 0.0.

![image](https://user-images.githubusercontent.com/33261105/146041451-a2aae099-a412-4e21-b677-bfda256dcf7f.png)
