### ISSUE TITLE
Update to xarray 0.20.0

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt_wflow#64]
Xarray > 0.20.0 has now an error instead of a deprecation for open mf_dataset.
See http://xarray.pydata.org/en/stable/whats-new.html#deprecations

This causes errors when reading for example era5_daily datasets to create wflow forcing.

**Comment by DirkEilander** [comment]
Important catch! Together with the deprecation of open_rasterio in favor of rioxarray there is some work for us to be done here !

**Comment by DirkEilander** [comment]
If I read the docs correctly, the error in open_mfdataset arises for the combined use of `concat_dim` and `combine_by_coords` arguments. This can easily be fixed by updating the kwargs in the data_catalog yml files, right?

**Comment by DirkEilander** [comment]
this should be fixed with the updated deltares_data.yml in https://github.com/DirkEilander/hydromt-artifacts/commit/5d80b3b48a78d6fbf1df89c88a1337ce3778e632
