### ISSUE TITLE
Add functions for water demands

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt_wflow#87]
Add first implementation new water demands input data for the new water demand allocation module in Wflow.Jl.

TODOs:

- [x] setup_domestic_demand: reproject_like of existing domestic demands grids (for now grids from Wada and Europe)
- [x] setup_industry_demand: reproject_like of existing industry demands grids (for now grids from Wada)
- [x] setup_irrigation_demand from MIRCA for irrigated areas and crop factors from FAO (and other needed data)
- [x] prepare a allocation map (where to look for available for each cell, based on admin level and subbasin) --> same or different per type of demand? If the same create a separate function setup_allocation_areas. If different do it inside the small setup_ functions.

**Comment by verseve** [comment]
Wflow.jl uses critical pressure heads (cm) for root water uptake reduction (Feddes): h1, h2, h3_h, h3_l and h4. Values for different crop types can be found in literature and in software packages like SWAP (e.g. https://edepot.wur.nl/222782) and HYDRUS. 
For rice (paddy) I did find the following values: 100, 55, -160, -250, -16000 based on Singh (https://edepot.wur.nl/121640). 

For irrigation areas in Wflow.jl two types are available: Paddy and NonPaddy. As Wflow.jl does not work with sub-grid land cover functionality this should be based on dominant land cover.

**Comment by markhegnauer** [comment]
I came across this dataset, if of interest: 

- Publication: https://www.nature.com/articles/s41597-022-01760-1
- Data: https://figshare.com/articles/dataset/A_data_set_of_distributed_global_population_and_water_withdrawal_from_1960_to_2020/19387406/2

**Comment by verseve** [comment]
### **Required input data for water demand and allocation.**

**Sectors domestic, industry and livestock:**
- `demand_gross` (gross water demand) [mm Δt⁻¹].
- `demand_net` (net water demand) [mm Δt⁻¹].

**Paddy (paddy irrigated crops (i.e. rice)):**
- `irrigation_areas` (irrigation areas) [-].
- `irrigation_efficiency` (irrigation efficiency) [-].
- `h_min` (minimum required water depth in the irrigated rice field) [mm].
- `h_max` (optimal water depth in the irrigated rice fields) [mm].
- `h_p` (water depth when rice field starts spilling water (overflow)) [mm].

**Non-paddy (non-paddy irrigated crops):**
- `irrigation_areas` (irrigation areas) [-].
- `irrigation_efficiency` (irrigation efficiency) [-].

**Input for paddy, non-paddy and other vegetation:**
- `kc` (crop coefficient) [-], as (monthly climatology).
- `h1`, `h_2`, `h3_high`, `h3_low`, `h4` (critical pressure heads for root water uptake reduction) [cm], see also [comment](https://github.com/Deltares/hydromt_wflow/issues/87#issuecomment-1254709648).
- `alpha_h1` (root water uptake reduction at `h1`) [-], either 0.0 or 1.0 (root water uptake not constrained during saturated conditions). 
- `rootfraction` (root fraction with depth) [-], see also [comment](https://github.com/Deltares/hydromt_wflow/issues/87#issuecomment-1254709648), by default a homogeneous root distribution is assumed in Wflow.

**Water allocation:**
- `frac_sw_used` (fraction surface water used) [-], we could follow the approach in this [paper](https://hess.copernicus.org/articles/22/789/2018/hess-22-789-2018.html).
- `areas` (allocation areas) [-], see also [comment](https://github.com/Deltares/hydromt_wflow/issues/87#issue-1250504571).

**Comment by verseve** [comment]
I think the variable `frac_sw_used` (`frac_sw_abstraction` is probably a better term) is sufficient for Wflow, the fraction groundwater used is then (1.0 - `frac_sw_used`). So, do we also need `frac_sw_gw_extraction`?

We could indeed base this on water use statistics (e.g. from FAO, often at country level), and condition this with a map of active/productive aquifers, similar to LISFLOOD. Or we could use for example the approach described in the [paper](https://hess.copernicus.org/articles/22/789/2018/hess-22-789-2018.html) mentioned in the comment above.

**Comment by verseve** [comment]
An approach to check if irrigation is required during a time step for irrigation areas is to use the crop factor valid for that time step and a crop factor threshold (e.g. a value of 0.2 for `NonPaddy` areas and a value of 0.75 for `Paddy` areas used by models like PCR-GLOBWB and CWATM). 

As we do not use a crop factor climatology/ time series in Wflow for water demand, another more suitable approach is to use the leaf area index time series (climatology/forcing) for determining the growing season of irrigated crops. See also the following links for more detailed information [Global Variability of Simulated and Observed Vegetation Growing Season](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2018JG004881), [CRESCENDO](https://bg.copernicus.org/articles/18/2405/2021/) and [github code](https://github.com/daniele-peano/4GST). 

Not sure if we need to follow this approach completely in hydromt_wflow (perhaps Eq. 2 in Peano et al. is already sufficient), but a climatology map with a parameter that indicates whether crops are growing and irrigation can be applied would be very useful.
@JoostBuitink, @hboisgon and @dalmijn what do you think of this approach?

**Comment by JoostBuitink** [comment]
After a discussion with @verseve, we decided the following functionality to be added to the current PR:

- If paddy fields are present in the model, update the soil layers in the wflow model (and thus also update the `c` parameter):
  - Use the following default values: `[50, 100, 50, 200, 800, ]`. This stays close to the default values (`[100, 300, 800,]`), but allows us to add a layer below the paddy fields (from 15 to 20 cm depth) where we can restrict the conductivity to ensure water stays in the top 15 cm.
  - For the layer from 15 to 20 cm depth, we restrict the vertical conductivity to ~5 mm/day, by setting the `kvfrac` for that specific layer. For all other layers, this parameter remains 1.
- To determine when irrigation starts, we will the approach using LAI, since (1) we already use that data in our model setup, so we don't need to use yet another dataset, and (2) it makes sense to use the LAI as a measure when a crop starts growing. We add a layer to the staticmaps (`irrigation_trigger` or something) that essentially flags for each pixel and month whether irrigation can start.
