### ISSUE TITLE
fews_wflow: problems with existing export folder 

### ISSUE THREAD

**Issue by IMarth** [Deltares/hydromt_wflow#90]
When having an existing empty folder as export location for the hydromt-fews connection an error is thrown. 
FileNotFoundError: [Errno 2] No such file or directory: '..\\exportFolder\\Config\\MapLayerFiles\\wflow\\wflow_grids.csv'

When defining a new export folder in the .ini that is not existing yet, it works.

**Comment by DirkEilander** [comment]
fixed in #81
