### ISSUE TITLE
Move parameter mapping tables and add yml file

### ISSUE THREAD

**Issue by JoostBuitink** [Deltares/hydromt_wflow#94]
Move the parameter mapping tables from inside the code to the main directory of hydromt_wflow in order to improve transparency. Additionally, provide a yml file to read those files using the new DataFrameAdapter in hydromt. 

The argument containing the location/name of the mapping table will become a required argument in the future. For now, when no name is given, we'll revert back to the original way (linking name of lulc maps to mapping table), and throw a DeprecationWarning to prepare users for this breaking change.

**Comment by hboisgon** [comment]
I had a go at this in the hydromt_delft3dfm plugin. Examples are:

- data catalog: https://github.com/Deltares/HYDROLIB/blob/hydromt/hydrolib/hydromt_delft3dfm/data/parameters_data.yml
- inclusion in the code: https://github.com/Deltares/HYDROLIB/blob/hydromt/hydrolib/hydromt_delft3dfm/dflowfm.py

https://github.com/Deltares/HYDROLIB/blob/d768984b8bd6f3da20757fa7300accbaa805265c/hydrolib/hydromt_delft3dfm/dflowfm.py#L116-L118

https://github.com/Deltares/HYDROLIB/blob/d768984b8bd6f3da20757fa7300accbaa805265c/hydrolib/hydromt_delft3dfm/dflowfm.py#L168
