### ISSUE TITLE
check dates in setup_*_forcing

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt_wflow#97]
For the test Piave basin the dates of the forcing and toml file don't match.
Check where this error originates from and make sure that the toml file dates align with the forcing data in setup_*_forcing.

**Comment by hboisgon** [comment]
I see indeed that when building the forcing for a larger period than available in the source_data no warning happens or the toml is also not updated.

The decision is to send a warning that not all requested dates are available and to update the start and end time in the config to the range available in the source_data
